/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./pages/__root"
import { Route as MonitorImport } from "./pages/monitor"
import { Route as IndexImport } from "./pages/index"
import { Route as MonitorIndexImport } from "./pages/monitor/index"
import { Route as MobileIndexImport } from "./pages/mobile/index"
import { Route as LoginIndexImport } from "./pages/login/index"
import { Route as MonitorIdImport } from "./pages/monitor/$id"

// Create/Update Routes

const MonitorRoute = MonitorImport.update({
  path: "/monitor",
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any)

const MonitorIndexRoute = MonitorIndexImport.update({
  path: "/",
  getParentRoute: () => MonitorRoute,
} as any)

const MobileIndexRoute = MobileIndexImport.update({
  path: "/mobile/",
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  path: "/login/",
  getParentRoute: () => rootRoute,
} as any)

const MonitorIdRoute = MonitorIdImport.update({
  path: "/$id",
  getParentRoute: () => MonitorRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    "/monitor": {
      preLoaderRoute: typeof MonitorImport
      parentRoute: typeof rootRoute
    }
    "/monitor/$id": {
      preLoaderRoute: typeof MonitorIdImport
      parentRoute: typeof MonitorImport
    }
    "/login/": {
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    "/mobile/": {
      preLoaderRoute: typeof MobileIndexImport
      parentRoute: typeof rootRoute
    }
    "/monitor/": {
      preLoaderRoute: typeof MonitorIndexImport
      parentRoute: typeof MonitorImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  MonitorRoute.addChildren([MonitorIdRoute, MonitorIndexRoute]),
  LoginIndexRoute,
  MobileIndexRoute,
])

/* prettier-ignore-end */
